theme = "rose_pine"

[editor]
line-number = "absolute"
scroll-lines = 15
auto-pairs = true
scrolloff = 15
mouse = false
continue-comments = false
#auto-info = false #disable hints
text-width = 80
rulers = [81]
end-of-line-diagnostics = "hint"
jump-label-alphabet = "tnseriaoplvmgjbkdhfuc,"
completion-trigger-len = 5

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "ê´¥"



[keys.normal]
X = ["extend_line_above", "select_mode"]
x = ["extend_line_below", "select_mode"]
s = "goto_word"

C-l = "jump_view_right"
C-h = "jump_view_left"
C-k = "jump_view_up"
C-j = "jump_view_down"


[keys.select]
X = "extend_line_above"


[keys.normal.g]
q = [":reflow"]

[keys.normal."space"]
f = "file_picker_in_current_directory"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
