[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.svelte-language-server]
command = "svelte-language-server"

[language-server.pyrefly]
command = "pyrefly"
args = [ "lsp" ]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.ols]
command = "ols"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.sqls]
command = "sqls"

[language-server.gleam-lsp]
command = "gleam"
args = ["lsp"]

# languages
[[language]]
name = "python"
language-servers = [ "pyrefly" ]

[[language]]
name = "odin"
language-servers = [ "ols" ]

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "sql"
language-servers = [ "sqls" ]

[[language]]
name = "gleam"
language-servers = [ "gleam-lsp" ]
